package ma.oncf.digital.entity;
// Generated Jun 14, 2019 9:44:28 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Faq generated by hbm2java
 */
@Entity
@Table(name="faq"
    ,schema="public"
)
public class Faq  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idFaq;
     private String question;
     private String reponse;
     private Integer flag;

    public Faq() {
    }

	
    public Faq(int idFaq) {
        this.idFaq = idFaq;
    }
    public Faq(int idFaq, String question, String reponse, Integer flag) {
       this.idFaq = idFaq;
       this.question = question;
       this.reponse = reponse;
       this.flag = flag;
    }
   
     @Id 

    
    @Column(name="id_faq", unique=true, nullable=false)
    public int getIdFaq() {
        return this.idFaq;
    }
    
    public void setIdFaq(int idFaq) {
        this.idFaq = idFaq;
    }

    
    @Column(name="question")
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }

    
    @Column(name="reponse")
    public String getReponse() {
        return this.reponse;
    }
    
    public void setReponse(String reponse) {
        this.reponse = reponse;
    }

    
    @Column(name="flag")
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }




}


