package ma.oncf.digital.entity;
// Generated Jun 14, 2019 9:44:28 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Marche generated by hbm2java
 */
@Entity
@Table(name = "marche", schema = "public")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class Marche implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;

	private int idMarche;
	private Fournisseur fournisseur;
	private String codeMarche;
	private Date dateSignatureMarche;
	private Date dateCreation;
	private Date dateModification;
	private Set<Facture> factures = new HashSet<Facture>(0);
	private int statusMarche;

	public Marche() {
	}

	public Marche(int idMarche, Fournisseur fournisseur, String codeMarche) {
		this.idMarche = idMarche;
		this.fournisseur = fournisseur;
		this.codeMarche = codeMarche;
	}

	public Marche(int idMarche, Fournisseur fournisseur, String codeMarche, Date dateSignatureMarche, Date dateCreation,
			Date dateModification, Set<Facture> factures, int statusMarche) {
		this.idMarche = idMarche;
		this.fournisseur = fournisseur;
		this.codeMarche = codeMarche;
		this.dateSignatureMarche = dateSignatureMarche;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.factures = factures;
		this.statusMarche = statusMarche;
	}

	@Id
	@Column(name = "id_marche", unique = true, nullable = false)
	public int getIdMarche() {
		return this.idMarche;
	}

	public void setIdMarche(int idMarche) {
		this.idMarche = idMarche;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fournisseur_id_fournisseur", nullable = false)
	public Fournisseur getFournisseur() {
		return this.fournisseur;
	}

	public void setFournisseur(Fournisseur fournisseur) {
		this.fournisseur = fournisseur;
	}

	@Column(name = "code_marche", nullable = false, length = 70)
	public String getCodeMarche() {
		return this.codeMarche;
	}

	public void setCodeMarche(String codeMarche) {
		this.codeMarche = codeMarche;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_signature_marche", length = 13)
	public Date getDateSignatureMarche() {
		return this.dateSignatureMarche;
	}

	public void setDateSignatureMarche(Date dateSignatureMarche) {
		this.dateSignatureMarche = dateSignatureMarche;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_creation", length = 13)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_modification", length = 13)
	public Date getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(Date dateModification) {
		this.dateModification = dateModification;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marche")
	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}

	@Column(name = "statut_marche")
	public int getStatusMarche() {
		return statusMarche;
	}

	public void setStatusMarche(int statusMarche) {
		this.statusMarche = statusMarche;
	}

}
