package ma.oncf.digital.entity;
// Generated Jun 14, 2019 9:44:28 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Reclamation generated by hbm2java
 */
@Entity
@Table(name="reclamation"
    ,schema="public"
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Reclamation  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idReclamation;
     private Fournisseur fournisseur;
     private TypeDemande typeDemande;
     private String objet;
     private String contenu;
     private Date reclamationDate;

    public Reclamation() {
    }

	
    public Reclamation(int idReclamation) {
        this.idReclamation = idReclamation;
    }
    public Reclamation(int idReclamation, Fournisseur fournisseur, TypeDemande typeDemande, String objet, String contenu, Date reclamationDate) {
       this.idReclamation = idReclamation;
       this.fournisseur = fournisseur;
       this.typeDemande = typeDemande;
       this.objet = objet;
       this.contenu = contenu;
       this.reclamationDate = reclamationDate;
    }
   
    @Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id_reclamation", unique=true, nullable=false,columnDefinition = "serial")
    public int getIdReclamation() {
        return this.idReclamation;
    }
    
    public void setIdReclamation(int idReclamation) {
        this.idReclamation = idReclamation;
    }

@ManyToOne(fetch=FetchType.LAZY)
@JsonIgnore
    @JoinColumn(name="fournisseur_id_fournisseur")
    public Fournisseur getFournisseur() {
        return this.fournisseur;
    }
    
    public void setFournisseur(Fournisseur fournisseur) {
        this.fournisseur = fournisseur;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_demande_id_type_demande")
    public TypeDemande getTypeDemande() {
        return this.typeDemande;
    }
    
    public void setTypeDemande(TypeDemande typeDemande) {
        this.typeDemande = typeDemande;
    }

    
    @Column(name="objet")
    public String getObjet() {
        return this.objet;
    }
    
    public void setObjet(String objet) {
        this.objet = objet;
    }

    
    @Column(name="contenu")
    public String getContenu() {
        return this.contenu;
    }
    
    public void setContenu(String contenu) {
        this.contenu = contenu;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="reclamation_date", length=13)
    public Date getReclamationDate() {
        return this.reclamationDate;
    }
    
    public void setReclamationDate(Date reclamationDate) {
        this.reclamationDate = reclamationDate;
    }
    




}


