package ma.oncf.digital.entity;
// Generated Jun 14, 2019 9:44:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TypeDemande generated by hbm2java
 */
@Entity
@Table(name="type_demande"
    ,schema="public"
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TypeDemande  implements java.io.Serializable {


     private int idTypeDemande;
     private String libelleTypeDemande;
     private Integer flag;
     private String mailDestintaire;
     private Set<Reclamation> reclamations = new HashSet(0);

    public TypeDemande() {
    }

	
    public TypeDemande(int idTypeDemande) {
        this.idTypeDemande = idTypeDemande;
    }
    public TypeDemande(int idTypeDemande, String libelleTypeDemande, Integer flag, String mailDestintaire, Set reclamations) {
       this.idTypeDemande = idTypeDemande;
       this.libelleTypeDemande = libelleTypeDemande;
       this.flag = flag;
       this.mailDestintaire = mailDestintaire;
       //this.reclamations = reclamations;
    }
   
     @Id 

    
    @Column(name="id_type_demande", unique=true, nullable=false)
    public int getIdTypeDemande() {
        return this.idTypeDemande;
    }
    
    public void setIdTypeDemande(int idTypeDemande) {
        this.idTypeDemande = idTypeDemande;
    }

    
    @Column(name="libelle_type_demande")
    public String getLibelleTypeDemande() {
        return this.libelleTypeDemande;
    }
    
    public void setLibelleTypeDemande(String libelleTypeDemande) {
        this.libelleTypeDemande = libelleTypeDemande;
    }

    
    @Column(name="flag")
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    
    @Column(name="mail_destintaire", length=120)
    public String getMailDestintaire() {
        return this.mailDestintaire;
    }
    
    public void setMailDestintaire(String mailDestintaire) {
        this.mailDestintaire = mailDestintaire;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="typeDemande")
@JsonIgnore
    public Set<Reclamation> getReclamations() {
        return this.reclamations;
    }
    
    public void setReclamations(Set<Reclamation> reclamations) {
        this.reclamations = reclamations;
    }




}


